### PR TITLE
Added AuthInterface implementation for the User.

### PR DESCRIPTION
**Pull request by armpogart**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

`Yiisoft\Auth\AuthInterface` implementation for the `User` class to use it in `Auth` middleware.
I'm not sure on naming and having default `authUrl` predefined.

P.S. Will add tests as soon you give the green light.

### CODE REVIEW

**Comment by rustamwin** [comment]
https://github.com/yiisoft/yii-web/issues/275#issuecomment-666676216?

**Comment by armpogart** [comment]
I've looked through that issue, but thought it concerns only cookie and session.
If `User` will be moved to `Auth` it will also make the `auth` package to depend on cookie and session packages.

I think `User` is more specific for yii framework and not overall community as a separate package. I'm not sure on usability of `User` outside the framework. User implementation is usually strongly coupled to database entity or the code in other frameworks or frameworkless applications, so I see little value in having it there.
What about `AccessCheckerInterface` in `User` class in that case?

If the decision will be made to move it to `auth` package, this can also be moved with it as it is in the same folder.

**Comment by samdark** [comment]
1. Would that make `AutoLoginMiddleware` duplicate functionality?
2. Should we do something about `User::loginByAccessToken()` then?

**Comment by armpogart** [comment]
> 1. Would that make `AutoLoginMiddleware` duplicate functionality?
> 2. Should we do something about `User::loginByAccessToken()` then?

1. I'm not sure how this is supposed to duplicate `AutLoginMiddleware` functionality. This is `AuthInterface` functionality for `Auth` middleware that will be used on route or group of routes to ensure that the user is already logged in based purely on session. `AutoLoginMiddleware` on the other hand logs in user even if the session is expired based on some cookie. I don't see anything in common.
2. `User::loginByAccessToken` must be removed from the `User` in my opinion. We can have another `IdentityInterface` implementation and middleware specific for that. And we can have another `AuthInterface` implementation specifically for that, as it will be used mainly to authenticate API requests and not general user.

**Comment by samdark** [comment]
Alright. Does it make sense to do point 2 in this pull request?

**Comment by armpogart** [comment]
No, I've drafted all things needed for that in separate issue #304. There are a couple of packages that need to be refined for that (not only yii-web).

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
👍

**Pull request merged**
