### PR TITLE
Fix User identity stuck in RoadRunner environment

### PR DESCRIPTION
**Pull request by rustamwin**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | -
| Fixed issues  | #162

### CODE REVIEW

**Comment by samdark** [comment]
@rustamwin have you tested it locally?

**Comment by rustamwin** [comment]
I haven't tested yet

**Comment by rob006** [comment]
Wait, why user object is shared between two separate requests?

**Comment by samdark** [comment]
@rob006 whole container is shared. That's how RoadRunner gains its performance. We can deal with it in three ways:

1. Avoid having state in services.
2. Clean up state individually for services that need it.
3. Have a special DI container mode for services that will be reset on each request.

**Comment by samdark** [comment]
This change won't fix the problem for sure.

**Comment by rob006** [comment]
@samdark Can we detect which services depends (directly on indirectly) on request? Basically all of them should be reset.

**Comment by samdark** [comment]
@rob006 I don't think we can do that in runtime.

**Pull request closed without merging**
