### PR TITLE
Refactored for Yii 3.0 support

### PR DESCRIPTION
**Pull request by terabytesoftw**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Fixed issues  | #37

### CODE REVIEW

**Comment by hiqsol** [comment]
Thank you! What you propose is a working solution.
But please look at how it should be done a new way.
I hope you'll catch the ideas: use DI, try not to use init and Yii helper.
That is not an ideal solution too. (And not tested)

**Comment by hiqsol** [comment]
No, in general case no need for Application in model.

**Comment by terabytesoftw** [comment]
it must be implemented, or it is already done.

**Comment by machour** [comment]
Why would you need $this->app in models ? For translations ?

**Comment by terabytesoftw** [comment]
@machour, we need $this->app and $this->getApp() in models.

**Pull request closed without merging**
